database:
  mongodb_uri: "mongodb://localhost:27017"
  db_name: "stock_market_data"

broker:
  icici_direct:
    api_key: "B4G62970~069j1K3~+573*1483_G3347"
    session_token: "(462L717%5p191B6807*717=779837lJ"
    session_expiry: "24h"

logging:
  level: "INFO"
  file: "logs/data_service.log"

services:
  historical_data: true
  real_time_data: true
  fno_data: true
