icicidirect:
  access_token: encrypted:gAAAAABnZYqAeOZV9bCQU2Z-prQLzJHdaflFJvmF0CnQ6jsRFPK5W9k07NWRzQ3mjGKtwSBYuIRkOGaUHZZtBNnBACRYsM2JbwY7rc8AnwxMVPCDkXJyomk=
  api_key: encrypted:gAAAAABnZYqAPAThdQpbLaZNX90KnVp1oy2BK8rCo0uNtoWlRg2ugZesPUw_KthbWw596uSVC1H8BeObeP8cPMT4vcd7hZkF2A==
  api_secret: encrypted:gAAAAABnZYqA6fZ6zcfbQsoXPR7tPO1bw4jdGUqpmc2uo6PQ1sH5OgbZIxrUqIsC5zmsenP3YY2jIjK5m6SCSNjEBZbT8cOXlA==
