database:
  mongodb_uri: "mongodb://localhost:27017"
  db_name: "stock_market_data"

broker:
  icici_direct:
    api_key: "your_api_key"
    session_token: "your_session_key"
    session_expiry: "24h"

logging:
  level: "INFO"
  file: "logs/data_service.log"

services:
  historical_data: true
  real_time_data: true
  fno_data: true
