# Placeholders for sensitive information
api_credentials:
  breeze:
    key_placeholder: B4G62970~069j1K3~+573*1483_G3347
    secret_placeholder: (462L717%5p191B6807*717=779837lJ

  yfinance:
    token_placeholder: to_be_replaced

database:
  connection:
    username_placeholder: to_be_replaced
    password_placeholder: to_be_replaced